# Generated by Django 2.2.5 on 2019-09-10 01:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='氏名')),
                ('mail_address', models.CharField(max_length=50, verbose_name='メールアドレス')),
                ('organization', models.CharField(max_length=50, verbose_name='所属組織')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
            ],
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('summary', models.CharField(max_length=210, verbose_name='概要')),
                ('description', models.CharField(max_length=990, verbose_name='詳細説明')),
                ('plugin', models.FileField(upload_to='plugins/')),
                ('tsrget', models.CharField(max_length=210, verbose_name='操作対象')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecomockapp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('summary', models.CharField(max_length=210, verbose_name='概要')),
                ('description', models.CharField(max_length=990, verbose_name='詳細説明')),
                ('scenario', models.FileField(upload_to='scenarios/')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecomockapp.Author')),
                ('require', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecomockapp.Plugin')),
            ],
        ),
    ]
