# Generated by Django 2.2.5 on 2019-09-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomockapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugin',
            old_name='tsrget',
            new_name='target',
        ),
        migrations.AlterField(
            model_name='plugin',
            name='plugin',
            field=models.FileField(upload_to='plugins/', verbose_name='プラグインモジュール'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario',
            field=models.FileField(upload_to='scenarios/', verbose_name='シナリオモジュール'),
        ),
    ]
